import { EmbedBuilder } from "discord.js";

const createEmbed = (uuid, first_name, last_name, birthday, currentPage = 0, totalPages = 1) => {
  return (
    new EmbedBuilder()
      // .setColor(0xd11013)
      .setColor(0x6943e8)
      .setTitle(first_name + " " + last_name + "'s Info")
      // .setAuthor({
      //   name: "GovLink",
      //   iconURL: "http://localhost:3000/assets/govlink-logo.png", // Full URL needed
      //   url: "https://youtube.com",
      // })
      .addFields(
        { name: "UUID", value: uuid },
        { name: "\u200B", value: "\u200B" },
        { name: "First Name", value: first_name, inline: true },
        { name: "Last Name", value: last_name, inline: true },
        { name: "Birthday", value: birthday, inline: true }
      )
      .setFooter({ text: `Page ${currentPage + 1}/${totalPages} • Generated by FakerAPI` })
      .setTimestamp()
  );
};

// inside a command, event listener, etc.
const exampleEmbed = new EmbedBuilder()
  .setColor(0xd11013)
  .setTitle("Birthday Data of 10 Random People")
  // .setURL("https://discord.js.org/")
  // .setAuthor({
  //   name: "GovLink",
  //   iconURL: "/assets/govlink-logo.png",
  //   url: "https://youtube.com",
  // })
  .setDescription("Some description here")
  // .setThumbnail("https://i.imgur.com/AfFp7pu.png")
  .addFields(
    { name: "Regular field title", value: "Some value here" },
    { name: "\u200B", value: "\u200B" },
    { name: "Inline field title", value: "Some value here", inline: true }
  )
  .addFields({ name: "Inline field title", value: "Some value here", inline: true })
  // .setImage("https://i.imgur.com/AfFp7pu.png")
  .setTimestamp();
// .setFooter({ text: "Some footer text here", iconURL: "https://i.imgur.com/AfFp7pu.png" });

export { createEmbed };
